#!/bin/bash

# High Refresh Rate Script
# Sets monitor to highest available refresh rate permanently
# Based on Reddit and Arch Wiki recommendations
# Created by litebiter & auxmeet

# Colors
GREEN='\033[0;32m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
WHITE='\033[1;37m'
RED='\033[0;31m'
YELLOW='\033[1;33m'
NC='\033[0m'

echo -e "${CYAN}=== High Refresh Rate Setup ===${NC}"

# Check if X11 is running
if [ -z "$DISPLAY" ]; then
    echo -e "${RED}Error: X11 not running. DISPLAY environment variable not set.${NC}"
    echo -e "${YELLOW}This script requires an active X11 session.${NC}"
    exit 1
fi

# Check if xrandr is available
if ! command -v xrandr &> /dev/null; then
    echo -e "${RED}Error: xrandr not found. Install xorg-xrandr${NC}"
    exit 1
fi

echo -e "${BLUE}Detecting connected displays...${NC}"

# Get connected displays
CONNECTED_DISPLAYS=$(xrandr | grep " connected" | cut -d' ' -f1)

if [ -z "$CONNECTED_DISPLAYS" ]; then
    echo -e "${RED}No connected displays found${NC}"
    exit 1
fi

echo -e "${GREEN}Found connected displays:${NC}"
echo "$CONNECTED_DISPLAYS"
echo ""

# Set highest refresh rate for each display
for display in $CONNECTED_DISPLAYS; do
    echo -e "${BLUE}Processing display: $display${NC}"
    
    # Get current resolution
    CURRENT_MODE=$(xrandr | grep "^$display" -A 1 | grep -o "[0-9]*x[0-9]*" | head -n1)
    
    if [ -z "$CURRENT_MODE" ]; then
        echo -e "${YELLOW}Could not determine current resolution for $display${NC}"
        continue
    fi
    
    echo -e "${WHITE}Current resolution: $CURRENT_MODE${NC}"
    
    # Get available refresh rates for current resolution
    AVAILABLE_RATES=$(xrandr | grep "$CURRENT_MODE" | grep -o "[0-9]*\.[0-9]*" | sort -rn)
    
    if [ -z "$AVAILABLE_RATES" ]; then
        echo -e "${YELLOW}No refresh rates found for $CURRENT_MODE${NC}"
        continue
    fi
    
    echo -e "${WHITE}Available refresh rates:${NC}"
    echo "$AVAILABLE_RATES"
    
    # Get highest refresh rate
    HIGHEST_RATE=$(echo "$AVAILABLE_RATES" | head -n1)
    
    echo -e "${GREEN}Setting $display to $CURRENT_MODE at $HIGHEST_RATE Hz${NC}"
    
    # Set the refresh rate
    if xrandr --output "$display" --mode "$CURRENT_MODE" --rate "$HIGHEST_RATE"; then
        echo -e "${GREEN}✓ Successfully set $display to $HIGHEST_RATE Hz${NC}"
    else
        echo -e "${RED}✗ Failed to set refresh rate for $display${NC}"
    fi
    
    echo ""
done

# Create screenlayout directory (works with most WMs including i3, bspwm, etc.)
echo -e "${BLUE}Creating screenlayout script for automatic refresh rate setting...${NC}"

USER_HOME=$(getent passwd $(whoami) | cut -d':' -f6)
SCREENLAYOUT_DIR="$USER_HOME/.screenlayout"
SCRIPT_PATH="$(realpath "$0")"

mkdir -p "$SCREENLAYOUT_DIR"

# Generate xrandr commands for current displays
XRANDR_COMMANDS=""
for display in $CONNECTED_DISPLAYS; do
    CURRENT_MODE=$(xrandr | grep "^$display" -A 1 | grep -o "[0-9]*x[0-9]*" | head -n1)
    AVAILABLE_RATES=$(xrandr | grep "$CURRENT_MODE" | grep -o "[0-9]*\.[0-9]*" | sort -rn)
    HIGHEST_RATE=$(echo "$AVAILABLE_RATES" | head -n1)
    
    if [ -n "$CURRENT_MODE" ] && [ -n "$HIGHEST_RATE" ]; then
        XRANDR_COMMANDS="$XRANDR_COMMANDS xrandr --output $display --mode $CURRENT_MODE --rate $HIGHEST_RATE"
    fi
done

# Create screenlayout script
cat > "$SCREENLAYOUT_DIR/high-refresh-rate.sh" << EOF
#!/bin/bash
# Auto-generated by cachyos-optimization-tool
# Created by litebiter & auxmeet

$XRANDR_COMMANDS
EOF

chmod +x "$SCREENLAYOUT_DIR/high-refresh-rate.sh"
echo -e "${GREEN}Screenlayout script created at $SCREENLAYOUT_DIR/high-refresh-rate.sh${NC}"

# For NVIDIA users, also create nvidia-settings configuration
if command -v nvidia-settings &> /dev/null; then
    echo -e "${BLUE}Detected NVIDIA GPU - creating nvidia-settings configuration...${NC}"
    
    # Save current settings to ~/.nvidia-settings-rc
    nvidia-settings --load-config-only &> /dev/null || true
    
    # Create autostart for nvidia-settings
    AUTOSTART_DIR="$USER_HOME/.config/autostart"
    mkdir -p "$AUTOSTART_DIR"
    
    cat > "$AUTOSTART_DIR/nvidia-settings.desktop" << EOF
[Desktop Entry]
Type=Application
Name=NVIDIA Settings
Exec=nvidia-settings --load-config-only
Terminal=false
X-GNOME-Autostart-enabled=true
EOF
    
    echo -e "${GREEN}NVIDIA settings autostart created${NC}"
fi

# Add to .xinitrc for WMs that use it (i3, bspwm, etc.)
if [ -f "$USER_HOME/.xinitrc" ]; then
    if ! grep -q "screenlayout/high-refresh-rate.sh" "$USER_HOME/.xinitrc"; then
        echo "" >> "$USER_HOME/.xinitrc"
        echo "# Load high refresh rate settings" >> "$USER_HOME/.xinitrc"
        echo "$SCREENLAYOUT_DIR/high-refresh-rate.sh" >> "$USER_HOME/.xinitrc"
        echo -e "${GREEN}Added to .xinitrc${NC}"
    fi
fi

# For systemd user service (more reliable for Wayland/hybrid setups)
SYSTEMD_DIR="$USER_HOME/.config/systemd/user"
mkdir -p "$SYSTEMD_DIR"

cat > "$SYSTEMD_DIR/set-high-refresh-rate.service" << EOF
[Unit]
Description=Set High Refresh Rate on Login
After=graphical-session.target

[Service]
Type=oneshot
ExecStart=$SCREENLAYOUT_DIR/high-refresh-rate.sh
RemainAfterExit=no

[Install]
WantedBy=default.target
EOF

echo -e "${GREEN}Systemd service created at $SYSTEMD_DIR/set-high-refresh-rate.service${NC}"

# Enable the service
echo -e "${BLUE}Enabling systemd service...${NC}"
systemctl --user enable set-high-refresh-rate.service > /dev/null 2>&1
echo -e "${GREEN}Service enabled${NC}"

# Also add to autostart for desktop environments
AUTOSTART_DIR="$USER_HOME/.config/autostart"
mkdir -p "$AUTOSTART_DIR"

cat > "$AUTOSTART_DIR/set-high-refresh-rate.desktop" << EOF
[Desktop Entry]
Type=Application
Name=Set High Refresh Rate
Exec=$SCREENLAYOUT_DIR/high-refresh-rate.sh
Terminal=false
X-GNOME-Autostart-enabled=true
EOF

echo -e "${GREEN}Autostart entry created${NC}"

echo ""
echo -e "${GREEN}=== High Refresh Rate Setup Complete ===${NC}"
echo ""
echo -e "${WHITE}The highest refresh rate has been set for all connected displays${NC}"
echo -e "${WHITE}A systemd service has been created to maintain this setting${NC}"
echo ""
echo -e "${YELLOW}⚠ If you experience issues with specific refresh rates, you can manually set them:${NC}"
echo -e "${WHITE}xrandr --output <display> --mode <resolution> --rate <refresh_rate>${NC}"
echo ""
echo -e "${CYAN}Created by litebiter & auxmeet${NC}"